### ISSUE TITLE
Create frontend mvp

### ISSUE THREAD

**Issue by 0xekez** [envoylabs/whoami#14]
From a discussion with @the-frey we'll need the following pages for a whoami fronted MVP
- [x] #8 
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #13

**Comment by the-frey** [comment]
Could track this better via a milestone maybe? Have created one - good idea. But yes agree these are the moving parts 🙂 
Should be on this all day tomorrow so hopefully make some good progress now astarte/moneta testing is wrapping up

**Comment by 0xekez** [comment]
tracked elsewhere in the whoami-ui repo. Didn't see that had been created :)
