### ISSUE TITLE
Case-independent validation

### ISSUE THREAD

**Issue by the-frey** [envoylabs/whoami#44]
At the moment, we assume that all tokens are valid - i.e. two people can be

- `The-Frey`
- `the-frey`

But this is likely undesirable, and we should run a sense-check in the validation step in the contract.

**Comment by the-frey** [comment]
I would be surprised if services like Discord allow for both `TheFrey` and `thefrey` to exist, for example

**Comment by KorNatten** [comment]
Starname had the same problem. Also be careful if you allow dots. If people want to use it as a name to request tips or donations. Telegram, twitter, fb,... Automatically converts them in URL's which makes it very confusing.
